(function ensightenInit(){var ensightenOptions = {client: "hearst", clientId: 109, publishPath: "news", isPublic:0, serverComponentLocation: "nexus.ensighten.com/hearst/news/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/hearst/news/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Mon Mar 10 20:48:08 GMT 2014"};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(g){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is never available"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";this.err=a}function p(){for(var a=b.dataDefinitionIds.length,e=!0,c=0;c<a;c++){var d=b.dataDefinitions[b.dataDefinitionIds[c]];if(!d||null==d.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}
var d={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};d.version="1.16.0";d.nexus=g.nexus||"nexus.ensighten.com";d.rand=-1;d.options={interval:g.interval||100,erLoc:g.errorLocation||d.nexus+"/error/e.gif",scLoc:g.serverComponentLocation||d.nexus+"/"+g.client+"/serverComponent.php",sjPath:g.staticJavascriptPath||d.nexus+"/"+g.client+"/code/",alLoc:g.alertLocation||d.nexus+"/alerts/a.gif",publishPath:g.publishPath,isPublic:g.isPublic,client:g.client,clientId:g.clientId,enableTagAuditBeacon:g.enableTagAuditBeacon,
scUseCacheBuster:g.scUseCacheBuster};d.ruleList=[];d.exceptionList=[];d.ensightenVariables={};d.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;d.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;d.BeaconException=n;d.checkForInvalidDependencies=
function(a,e,c,l){for(a=0;a<c.length;a++)if("DEPENDENCYNEVERAVAILABLE"===c[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new d.DependencyNotAvailableException(l[a])),!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+d.options.scLoc,!1,a||!0,d.options.scUseCacheBuster)};
b.setVariable=function(a,b){d.ensightenVariables[a]=b};b.getVariable=function(a){return a in d.ensightenVariables?d.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<d.ruleList.length;a++)d.test(d.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();d.exceptionList.push(a);a=b.imageRequest(window.location.protocol+"//"+d.options.erLoc+"?msg="+a.message+"&lnn="+(a.lineNumber||
a.line)+"&fn="+(a.fileName||a.sourceURL)+"&cid="+d.options.clientId+"&client="+d.options.client+"&publishPath="+d.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=
!0,b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;d.ruleList.push(a);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<d.ruleList.length;b++)if(d.ruleList[b].id===a)return d.ruleList[b];return!1};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};d.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+d.toTwoChar(b.getMonth())+"-"+d.toTwoChar(b.getDate())+" "+d.toTwoChar(b.getHours())+":"+d.toTwoChar(b.getMinutes())+":"+d.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.date=b;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+d.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+d.options.clientId+
"&client="+d.options.client+"&publishPath="+d.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,c,l){var h=document.getElementsByTagName("script"),f;l=void 0!==l?l:!0;if(void 0!==e?e:1)for(f=0;f<h.length;f++)if(h[f].src===a&&h[f].readyState&&/loaded|complete/.test(h[f].readyState))return;if(c){c=!0==c&&"object"==typeof b.scDataObj?
b.scDataObj:c;d.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof c)for(f in c){f=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,f.length?e.length-f.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in c)e+=k+"="+c[k]+"&";e=e.slice(0,-1)+f;break}a+="?";l&&(a+="r="+d.rand+"&");a+="ClientID="+d.options.clientId+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var c=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in
c){if(!c[0]){setTimeout(arguments.callee,25);return}c=c[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.insertBefore(a,c.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,c){var d=document.getElementsByTagName("script"),h;c=d[0];for(h=0;h<d.length;h++)if(d[h].src===a&&d[h].readyState&&/loaded|complete/.test(d[h].readyState))try{b()}catch(f){window[ensightenOptions.ns].reportException(f)}finally{return}d=
document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};c.parentNode.insertBefore(d,c)};b.unobtrusiveAddEvent=function(a,
b,c){try{var d=a[b]?a[b]:function(){};a[b]=function(){c.apply(this,arguments);return d.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(c){window[ensightenOptions.ns].reportException(c)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,
deploymentId:c||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,c=0;c<a.length;++c)if(e=b.getRule(parseInt(a[c],10)),!e||!e.executionData.hasRun)return!1;return!0};
b.bindDependencyImmediate=function(a,e,c,l,h){var f=[];if(!d.checkForInvalidDependencies(e,l,c,h)){f.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,c,l,h){var f=[];if(!d.checkForInvalidDependencies(e,l,c,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});f.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});
if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,c,l,h){var f=[];if(!d.checkForInvalidDependencies(e,l,c,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});f.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,c,l,h){var f=[];if(!d.checkForInvalidDependencies(e,l,c,h)){f.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});f.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,
e,c,l,h){var f=[];if(!d.checkForInvalidDependencies(e,l,c,h)){f.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});f.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,c,l,h){var f=[];if(!d.checkForInvalidDependencies(e,l,c,h)){f.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});
f.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,c=0;c<e;c++){var d=a[c];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(d)&&b.dataDefinitionIds.push(d);else{for(var h=!1,f=b.dataDefinitionIds.length,
g=0;g<f;g++)if(b.dataDefinitionIds[g]===d){h=!0;break}h||b.dataDefinitionIds.push(d)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=
c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};
b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=
!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var q=function(){var a=[],b=!1,c=!1;return{add:function(d){b&&!c?d():"function"==typeof d&&(a[a.length]=d)},exec:function(){c=!0;do{var d=a;a=[];b=!0;for(var g=0;g<d.length;g++)try{d[g].call(window)}catch(f){window[ensightenOptions.ns].reportException(f)}}while(0<
a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=function(){return q()};d.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=
b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?d.timer=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(d.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,
15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===d.options.enableTagAuditBeacon&&window.setTimeout(function(){try{for(var a=[],e,c,l,h,f=0;f<d.ruleList.length;++f)c=d.ruleList[f],l=c.executionData.hasRun?"1":"0",h=c.deploymentId.toString()+"|"+c.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";b.imageRequest(window.location.protocol+"//"+d.nexus+"/"+g.client+"/"+g.publishPath+"/TagAuditBeacon.rnc?cid="+
g.clientId+"&data="+e+"&idx=0&r="+d.rand)}catch(m){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new d.BeaconException(m),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,d.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns].bindDOMParsed(function(){var g=window.performance;if(g){var g=g.timing||{},m="",n=g.navigationStart||0,p,d={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",
responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+g.navigationStart,b;for(b in d)void 0!==g[b]?(p=g[b]-n,m+="&"+d[b]+"="+(0<p?p:0)):m+="&"+d[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";g=ensightenOptions.staticJavascriptPath||"";m=g.indexOf(".com/");n=g.indexOf("/code/");g=g.substring(m+4,n)+"/perf.rnc";g+="?cid="+ensightenOptions.clientId+window[ensightenOptions.ns].timing;
window[ensightenOptions.ns].imageRequest("//"+b+g)}});
	Bootstrapper.dataDefinitionIds = [];Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();