document.write ('<IMG SRC="http://ad.doubleclick.net/ad/N9288.149925.MARTINIMEDIANETWORK/B8002316.13;sz=1x1;ord=1579314117?" BORDER=0 WIDTH=1 HEIGHT=1 ALT="Advertisement">\n');
document.write ('\n');
document.write ('<div style="display:none !important;" id="flite-click-macro-87229acf-72f6-4548-8871-90d8bbc8028d">http://tags.bluekai.com/site/17226?phint=event%3Dclick&phint=adv%3DKIA&phint=cmp%3DMartini/KIA_Q114_Interstitial_Desktop&phint=url%3Dmboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55&redir=http://oasc12.247realmedia.com/RealMedia/ads/click_lx.ads/mboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55/1579314117/x94/Martini/KIA_Q114_Interstitial_Desktop/KIA_Q114_Interstitial_Desktop2_BG.html/436c657573564c724372344141565577?</div>\n');
document.write ('\n');
document.write ('<script>\n');
document.write ('    (function() {\n');
document.write ('        var guid = "87229acf-72f6-4548-8871-90d8bbc8028d", o = window, r = "", m, s = "http:", e = encodeURIComponent, x = 0, f = document.createElement("script");\n');
document.write ('        o.FLITE=o.FLITE || {};\n');
document.write ('        o.FLITE.config = o.FLITE.config || {};\n');
document.write ('        o.FLITE.config[guid] = o.FLITE.config[guid] || {};\n');
document.write ('        o.FLITE.config[guid].cb = Math.random();\n');
document.write ('        o.FLITE.config[guid].ts = (+ new Date());\n');
document.write ('        try{ r = (top===self && top.location) ? top.location.href : document.referrer || (top.location && top.location.href) || "";}catch(er){x=1}\n');
document.write ('        try{ s = o.location && o.location.protocol === "https:"? o.location.protocol : s;}catch(er){x+=2}\n');
document.write ('        try{ m = r.match(new RegExp("[A-Za-z]+:[/][/][A-Za-z0-9.-]+")); } catch(er) {x+=4}\n');
document.write ('        try{ var fm = document.getElementById("flite-click-macro-" + guid); var c = (fm && (fm.innerText || fm.textContent || fm.innerHTML)) || ""; c = c.replace(/^\\');
document.write ('s+|\\');
document.write ('s+$/g, ""); o.FLITE.config[guid].ct = c; } catch(err) {x+=8}\n');
document.write ('        f.src = [s,"//r.flite.com/syndication/uscript.js?i=",e(guid),"&v=3&dep=LIGHTBOX,CHILD","&x=us",x,"&cb=",o.FLITE.config[guid].cb,"&d=",e((m && m[0]) || r)].join("");\n');
document.write ('        document.write(f.outerHTML);\n');
document.write ('        })();\n');
document.write ('</script>\n');
document.write ('\n');
document.write ('<noscript>\n');
document.write ('    <a style="text-decoration:none;display:block;border:0;" href="//r.flite.com/syndication/backuplink/i/87229acf-72f6-4548-8871-90d8bbc8028d?ct=http://tags.bluekai.com/site/17226?phint=event%3Dclick&phint=adv%3DKIA&phint=cmp%3DMartini/KIA_Q114_Interstitial_Desktop&phint=url%3Dmboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55&redir=http://oasc12.247realmedia.com/RealMedia/ads/click_lx.ads/mboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55/1579314117/x94/Martini/KIA_Q114_Interstitial_Desktop/KIA_Q114_Interstitial_Desktop2_BG.html/436c657573564c724372344141565577?" target="_blank">\n');
document.write ('        <img border="0" src="//r.flite.com/syndication/backupimage/i/87229acf-72f6-4548-8871-90d8bbc8028d?at="/>\n');
document.write ('    </a>\n');
document.write ('</noscript>\n');
document.write ('\n');
document.write ('<A HREF="http://ad.doubleclick.net/jump/N9288.149925.MARTINIMEDIANETWORK/B8002316.13;sz=1x1;ord=1579314117?">\n');
document.write ('<img src="http://core.insightexpressai.com/adServer/adServerESI.aspx?bannerID=260756&script=false&redir=http://core.insightexpressai.com/adserver/1pixel.gif">\n');
document.write ('<script src="http://js.moatads.com/martiniv2d38hdka12/moatad.js#moatClientLevel1=KIA&moatClientLevel2=&moatClientLevel3=Martini/KIA_Q114_Interstitial_Desktop&moatClientLevel4=KIA_Q114_Interstitial_Desktop2_BG&moatClientSlicer1=x94&moatClientSlicer2=mboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55" type="text/javascript"></script>\n');
document.write ('<noscript class="MOAT-martiniv2d38hdka12?moatClientLevel1=KIA&amp;moatClientLevel2=&amp;moatClientLevel3=Martini/KIA_Q114_Interstitial_Desktop&amp;moatClientLevel4=KIA_Q114_Interstitial_Desktop2_BG&amp;moatClientSlicer1=x94&amp;moatClientSlicer2=mboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55"></noscript>\n');
document.write ('<img height="1" width="1" src="http://tags.bluekai.com/site/17226?id=436c657573564c724372344141565577&phint=event%3Dimp&phint=adv%3DKIA&phint=cmp%3DMartini/KIA_Q114_Interstitial_Desktop&phint=url%3Dmboard.investopedia.com/KIA_Q12014_Desktop_Interstitial/L55">');
